[command]
default=ug-ants-launch recombine_bands_mesh_to_grid.py \
       ="${bands_dir}/regridded_band_*.nc" \
       =${output}

[env]
bands_dir=${ROSE_DATA}/ancil_band_regrid_mesh_to_grid_${CYLC_TASK_PARAM_scheme}
output=${ROSE_DATA}/${ROSE_TASK_NAME}.nc
