[command]
default=ug-ants-launch split_by_latitude_grid_to_mesh.py $source $output \
       =--target-mesh $mesh_file --target-mesh-name $mesh_name \
       =--number-of-bands $n_bands

[env]
mesh_file=${TEST_SOURCES_DIR}/global/C48/mesh.nc
mesh_name=dynamics
n_bands=$n_bands
output=${ROSE_DATA}/${ROSE_TASK_NAME}
source=${TEST_SOURCES_DIR}/global/n96/two_variable_multi_dimensional_synthetic_data.nc

[file:${ROSE_DATA}/${ROSE_TASK_NAME}]
mode=mkdir
