[command]
default=ug-ants-launch fill_missing_points.py ${source} ${output}
masked=ug-ants-launch fill_missing_points.py ${source} ${output} --target-mask ${mask}

[env]
mask=${TEST_SOURCES_DIR}/global/C12/target_mask_latitude_band.nc
output=${ROSE_DATA}/${ROSE_TASK_NAME}.nc
source=${TEST_SOURCES_DIR}/global/C12/missing_data.nc
