[command]
default=ug-ants-launch regrid_to_grid.py \
       =${source} ${target_grid} ${output} \
       =--horizontal-regrid-scheme ${regrid_scheme}
output_weights=ug-ants-launch regrid_to_grid.py \
              =${source} ${target_grid} ${output} \
              =--horizontal-regrid-scheme ${regrid_scheme} \
              =--output-weights ${output_weights}
use_input_weights=ug-ants-launch regrid_to_grid.py \
                 =${source} ${target_grid} ${output} \
                 =--horizontal-regrid-scheme ${regrid_scheme} \
                 =--input-weights ${input_weights}

[env]
input_weights=${TEST_SOURCES_DIR}/global/regrid_weights/C48_to_n96/${scheme}_weights.nc
mesh_name=dynamics
output=${ROSE_DATA}/${ROSE_TASK_NAME}.nc
output_weights=${ROSE_DATA}/${ROSE_TASK_NAME}_weights.nc
regrid_scheme=${scheme}
source=${TEST_SOURCES_DIR}/global/C48/surface_altitude.nc
target_grid=${TEST_SOURCES_DIR}/global/n96/surface_altitude.nc
