mode=rose_bunch

[bunch]
command-format=ug-ants-launch regrid_to_grid.py \
              =${source_dir}/source_band_%(band_num)s.nc \
              =${source_dir}/target_band_%(band_num)s.nc \
              =${output_dir}/regridded_band_%(band_num)s.nc \
              =--horizontal-regrid-scheme ${scheme}
pool-size=4

[bunch-args]
band_num=$band_nums

[env]
mesh_name=dynamics
output_dir=${ROSE_DATA}/${ROSE_TASK_NAME}
scheme=${CYLC_TASK_PARAM_scheme}
source_dir=${ROSE_DATA}/ancil_split_by_latitude_mesh_to_grid

[file:${ROSE_DATA}/${ROSE_TASK_NAME}]
mode=mkdir
