[command]
default=ug-ants-launch split_by_latitude_mesh_to_grid.py $source $target_grid $output \
       =--number-of-bands $n_bands

[env]
n_bands=$n_bands
output=${ROSE_DATA}/${ROSE_TASK_NAME}
source=${TEST_SOURCES_DIR}/global/C48/surface_altitude.nc
target_grid=${TEST_SOURCES_DIR}/global/n96/surface_altitude.nc

[file:${ROSE_DATA}/${ROSE_TASK_NAME}]
mode=mkdir
