# (C) Crown Copyright, Met Office. All rights reserved.
#
# This file is part of UG-ANTS and is released under the BSD 3-Clause license.
# See LICENSE.txt in the root of the repository for full licensing details.
"""Data to create synthetic cylc_dbs."""

"""Data to create a synthetic cylc database of task run duration data.

Contains 16 synthetic task runs with the keys "name", "time_run", "time_run_exit" and
"submit_num", matching the keys used in a Cylc db. These fields can be used to create
synthetic "task_jobs" and "task_states" tables.
"""
SYNTHETIC_TASK_DATA = [
    {
        "name": "install_cold",
        "time_run": "2024-06-24T15:17:33+01:00",
        "time_run_exit": "2024-06-24T15:17:48+01:00",
        "submit_num": "1",
    },
    {
        "name": "install_cold",
        "time_run": "2024-06-24T15:17:49+01:00",
        "time_run_exit": "2024-06-24T15:17:59+01:00",
        "submit_num": "2",
    },
    {
        "name": "ancil_regrid_to_mesh_conservative",
        "time_run": "2024-06-24T15:17:53+01:00",
        "time_run_exit": "2024-06-24T15:18:04+01:00",
        "submit_num": "1",
    },
    {
        "name": "build_docs",
        "time_run": "2024-06-24T15:17:54+01:00",
        "time_run_exit": "2024-06-24T15:18:16+01:00",
        "submit_num": "1",
    },
    {
        "name": "ancil_regrid_to_mesh_bilinear",
        "time_run": "2024-06-24T15:17:53+01:00",
        "time_run_exit": "2024-06-24T15:18:04+01:00",
        "submit_num": "1",
    },
    {
        "name": "ancil_fill_missing_points_masked_C12",
        "time_run": "2024-06-24T15:17:53+01:00",
        "time_run_exit": "2024-06-24T15:18:04+01:00",
        "submit_num": "1",
    },
    {
        "name": "black",
        "time_run": "2024-06-24T15:17:54+01:00",
        "time_run_exit": "2024-06-24T15:17:58+01:00",
        "submit_num": "1",
    },
    {
        "name": "ancil_fill_missing_points_isolated_C12",
        "time_run": "2024-06-24T15:17:53+01:00",
        "time_run_exit": "2024-06-24T15:18:03+01:00",
        "submit_num": "1",
    },
    {
        "name": "ancil_regrid_to_mesh_nearest",
        "time_run": "2024-06-24T15:17:54+01:00",
        "time_run_exit": "2024-06-24T15:18:03+01:00",
        "submit_num": "1",
    },
    {
        "name": "ruff",
        "time_run": "2024-06-24T15:17:54+01:00",
        "time_run_exit": "2024-06-24T15:18:03+01:00",
        "submit_num": "1",
    },
    {
        "name": "unittests",
        "time_run": "2024-06-24T15:17:54+01:00",
        "time_run_exit": "2024-06-24T15:18:15+01:00",
        "submit_num": "1",
    },
    {
        "name": "ancil_fill_missing_points_masked_overlap_C12",
        "time_run": "2024-06-24T15:17:53+01:00",
        "time_run_exit": "2024-06-24T15:18:04+01:00",
        "submit_num": "1",
    },
    {
        "name": "ancil_fill_missing_points_contiguous_C12",
        "time_run": "2024-06-24T15:17:53+01:00",
        "time_run_exit": "2024-06-24T15:18:04+01:00",
        "submit_num": "1",
    },
    {
        "name": "rose_ana_fill_missing_points",
        "time_run": "2024-06-24T15:18:09+01:00",
        "time_run_exit": "2024-06-24T15:18:11+01:00",
        "submit_num": "1",
    },
    {
        "name": "rose_ana_regrid_to_mesh",
        "time_run": "2024-06-24T15:18:09+01:00",
        "time_run_exit": "2024-06-24T15:18:13+01:00",
        "submit_num": "1",
    },
    {
        "name": "linkcheck",
        "time_run": "2024-06-24T15:18:19+01:00",
        "time_run_exit": "2024-06-24T15:18:25+01:00",
        "submit_num": "1",
    },
]


ANTS_ROSE_STEM_TEST_SUITE_TASK_NAMES = [
    "ancil_GLOMAP_aerosol_postproc",
    "ancil_GLOMAP_aerosol_preproc",
    "ancil_HadISST_preproc",
    "ancil_SST_mask",
    "ancil_add_lakes",
    "ancil_add_zeroth_level",
    "ancil_canopy_heights_preproc_simard",
    "ancil_canopy_heights_split0",
    "ancil_canopy_heights_split1",
    "ancil_canopy_heights_split2",
    "ancil_coastal_distance",
    "ancil_coastal_distance_unittests",
    "ancil_easy_aerosol_preproc_easy_absorption_lw",
    "ancil_easy_aerosol_preproc_easy_absorption_sw",
    "ancil_easy_aerosol_preproc_easy_asymmetry_lw",
    "ancil_easy_aerosol_preproc_easy_asymmetry_sw",
    "ancil_easy_aerosol_preproc_easy_cdnc",
    "ancil_easy_aerosol_preproc_easy_extinction_lw",
    "ancil_easy_aerosol_preproc_easy_extinction_sw",
    "ancil_generate_masks_split0",
    "ancil_generate_masks_split1",
    "ancil_generate_masks_split2",
    "ancil_lai_preproc",
    "ancil_lai_split0",
    "ancil_lai_split1",
    "ancil_lai_split2",
    "ancil_lake_depth_preproc",
    "ancil_lct_cci_split0",
    "ancil_lct_cci_split1",
    "ancil_lct_cci_split2",
    "ancil_lct_igbp_split0",
    "ancil_lct_igbp_split1",
    "ancil_lct_igbp_split2",
    "ancil_lct_ite_split0",
    "ancil_lct_ite_split1",
    "ancil_lct_ite_split2",
    "ancil_lct_postproc_c4_split0",
    "ancil_lct_postproc_c4_split1",
    "ancil_lct_postproc_c4_split2",
    "ancil_lct_preproc_cci_split0",
    "ancil_lct_preproc_cci_split1",
    "ancil_lct_preproc_cci_split2",
    "ancil_lct_preproc_igbp_split0",
    "ancil_lct_preproc_igbp_split1",
    "ancil_lct_preproc_igbp_split2",
    "ancil_lct_preproc_ite_split0",
    "ancil_lct_preproc_ite_split1",
    "ancil_lct_preproc_ite_split2",
    "ancil_orographic_formdrag_preproc",
    "ancil_orographic_formdrag_split0",
    "ancil_orographic_formdrag_split1",
    "ancil_orographic_formdrag_split2",
    "ancil_orographic_wavedrag_blended_max_slope_0p01_max_smooth_1_globe30_split0",
    "ancil_orographic_wavedrag_blended_max_slope_0p01_max_smooth_1_globe30_split1",
    "ancil_orographic_wavedrag_blended_max_slope_0p01_max_smooth_1_globe30_split2",
    "ancil_orographic_wavedrag_blended_max_slope_0p01_max_smooth_1_gmted_ramp2_split0",
    "ancil_orographic_wavedrag_blended_max_slope_0p01_max_smooth_1_gmted_ramp2_split1",
    "ancil_orographic_wavedrag_blended_max_slope_0p01_max_smooth_1_gmted_ramp2_split2",
    "ancil_orographic_wavedrag_epsilon_default_gmted_ramp2_split0",
    "ancil_orographic_wavedrag_epsilon_default_gmted_ramp2_split1",
    "ancil_orographic_wavedrag_epsilon_default_gmted_ramp2_split2",
    "ancil_orographic_wavedrag_epsilon_value_globe30_split0",
    "ancil_orographic_wavedrag_epsilon_value_globe30_split1",
    "ancil_orographic_wavedrag_epsilon_value_globe30_split2",
    "ancil_orographic_wavedrag_epsilon_value_gmted_ramp2_split0",
    "ancil_orographic_wavedrag_epsilon_value_gmted_ramp2_split1",
    "ancil_orographic_wavedrag_epsilon_value_gmted_ramp2_split2",
    "ancil_orographic_wavedrag_epsilon_value_rotated_pole_LAM_split0",
    "ancil_orographic_wavedrag_epsilon_value_rotated_pole_LAM_split1",
    "ancil_orographic_wavedrag_epsilon_value_rotated_pole_LAM_split2",
    "ancil_orographic_wavedrag_preproc_globe30",
    "ancil_orographic_wavedrag_preproc_gmted_ramp2",
    "ancil_orography_filtered_preproc_globe30",
    "ancil_orography_filtered_preproc_gmted_ramp2",
    "ancil_orography_mean_blended_max_slope_0p01_max_smooth_1_globe30_split0",
    "ancil_orography_mean_blended_max_slope_0p01_max_smooth_1_globe30_split1",
    "ancil_orography_mean_blended_max_slope_0p01_max_smooth_1_globe30_split2",
    "ancil_orography_mean_blended_max_slope_0p01_max_smooth_1_gmted_ramp2_split0",
    "ancil_orography_mean_blended_max_slope_0p01_max_smooth_1_gmted_ramp2_split1",
    "ancil_orography_mean_blended_max_slope_0p01_max_smooth_1_gmted_ramp2_split2",
    "ancil_orography_mean_epsilon_default_gmted_ramp2_split0",
    "ancil_orography_mean_epsilon_default_gmted_ramp2_split1",
    "ancil_orography_mean_epsilon_default_gmted_ramp2_split2",
    "ancil_orography_mean_epsilon_value_globe30_split0",
    "ancil_orography_mean_epsilon_value_globe30_split1",
    "ancil_orography_mean_epsilon_value_globe30_split2",
    "ancil_orography_mean_epsilon_value_gmted_ramp2_split0",
    "ancil_orography_mean_epsilon_value_gmted_ramp2_split1",
    "ancil_orography_mean_epsilon_value_gmted_ramp2_split2",
    "ancil_orography_mean_epsilon_value_rotated_pole_LAM_split0",
    "ancil_orography_mean_epsilon_value_rotated_pole_LAM_split1",
    "ancil_orography_mean_epsilon_value_rotated_pole_LAM_split2",
    "ancil_orography_unfiltered_preproc_globe30",
    "ancil_orography_unfiltered_preproc_gmted_ramp2",
    "ancil_ozone_redistribution_360_day",
    "ancil_ozone_redistribution_gregorian",
    "ancil_prescribed_time_varying_veg_split0",
    "ancil_prescribed_time_varying_veg_split1",
    "ancil_prescribed_time_varying_veg_split2",
    "ancil_radiation_parameters_split0",
    "ancil_radiation_parameters_split1",
    "ancil_radiation_parameters_split2",
    "ancil_regrid_um_to_mesh",
    "ancil_river_routing_1d_river_coupling_split0",
    "ancil_river_routing_1d_river_coupling_split1",
    "ancil_river_routing_1d_river_coupling_split2",
    "ancil_river_routing_gc4_split0",
    "ancil_river_routing_gc4_split1",
    "ancil_river_routing_gc4_split2",
    "ancil_river_routing_preproc",
    "ancil_river_storage",
    "ancil_river_storage_preproc",
    "ancil_soil_albedo_preproc",
    "ancil_soil_albedo_split0",
    "ancil_soil_albedo_split1",
    "ancil_soil_albedo_split2",
    "ancil_soil_dust_split0",
    "ancil_soil_dust_split1",
    "ancil_soil_dust_split2",
    "ancil_soil_roughness_preproc_prigent12",
    "ancil_soil_roughness_split0",
    "ancil_soil_roughness_split1",
    "ancil_soil_roughness_split2",
    "ancil_soils_clapp_hornberger_split0",
    "ancil_soils_clapp_hornberger_split1",
    "ancil_soils_clapp_hornberger_split2",
    "ancil_soils_preproc",
    "ancil_soils_preproc_clapp_hornberger",
    "ancil_sst_seaice_HadISST_split0",
    "ancil_sst_seaice_HadISST_split1",
    "ancil_sst_seaice_HadISST_split2",
    "ancil_sst_seaice_oper_AMM15_UKV_split0",
    "ancil_sst_seaice_oper_AMM15_UKV_split1",
    "ancil_sst_seaice_oper_AMM15_UKV_split2",
    "ancil_sst_seaice_postproc",
    "ancil_sst_seaice_preproc_HadISST",
    "ancil_sst_seaice_preproc_oper_AMM15_UKV",
    "ancil_time_header_postproc",
    "ancil_topographic_index_preproc",
    "ancil_topographic_index_split0",
    "ancil_topographic_index_split1",
    "ancil_topographic_index_split2",
    "ancil_ukca_anthropogenic_preproc",
    "ancil_ukca_anthropogenic_split0",
    "ancil_ukca_anthropogenic_split1",
    "ancil_ukca_anthropogenic_split2",
    "ancil_ukca_biomass_preproc",
    "ancil_ukca_biomass_split0",
    "ancil_ukca_biomass_split1",
    "ancil_ukca_biomass_split2",
    "ancil_ukca_translate_gfed",
    "black",
    "canopy_heights_unittests",
    "flake8",
    "install_cold",
    "isort",
    "lai_preproc_unittests",
    "lai_unittests",
    "lct_unittests",
    "move_lct_files_split0",
    "move_lct_files_split1",
    "move_lct_files_split2",
    "orography_unittests",
    "ozone_redistribution_unittests",
    "prescribed_time_varying_veg_unittests",
    "river_routing_unittests",
    "river_storage_unittests",
    "rose_ana_GLOMAP_aerosol_postproc",
    "rose_ana_GLOMAP_aerosol_preproc",
    "rose_ana_HadISST_preproc",
    "rose_ana_SST_mask",
    "rose_ana_add_zeroth_level",
    "rose_ana_canopy_heights",
    "rose_ana_coastal_distance",
    "rose_ana_data_preparation",
    "rose_ana_easy_aerosol_preproc",
    "rose_ana_lai",
    "rose_ana_lake_depth_preproc",
    "rose_ana_lct",
    "rose_ana_lct_cci_mask_split0",
    "rose_ana_lct_cci_mask_split1",
    "rose_ana_lct_cci_mask_split2",
    "rose_ana_lct_igbp_mask_split0",
    "rose_ana_lct_igbp_mask_split1",
    "rose_ana_lct_igbp_mask_split2",
    "rose_ana_lct_ite_mask_split0",
    "rose_ana_lct_ite_mask_split1",
    "rose_ana_lct_ite_mask_split2",
    "rose_ana_masks",
    "rose_ana_orographic_formdrag",
    "rose_ana_orographic_wavedrag_LAM",
    "rose_ana_orographic_wavedrag_globe30",
    "rose_ana_orographic_wavedrag_gmted_ramp2",
    "rose_ana_orography_blended_globe30",
    "rose_ana_orography_blended_gmted_ramp2",
    "rose_ana_orography_blended_mean_globe30",
    "rose_ana_orography_mean_LAM",
    "rose_ana_orography_mean_globe30",
    "rose_ana_orography_mean_gmted_ramp2",
    "rose_ana_ozone_redistribution",
    "rose_ana_prescribed_time_varying_veg",
    "rose_ana_radiation_parameters",
    "rose_ana_regrid_um_to_mesh",
    "rose_ana_river_routing",
    "rose_ana_river_storage",
    "rose_ana_soil_albedo",
    "rose_ana_soil_dust",
    "rose_ana_soil_roughness",
    "rose_ana_soils",
    "rose_ana_sst_seaice",
    "rose_ana_time_header_postproc",
    "rose_ana_topographic_index",
    "rose_ana_ukca_anthropogenic",
    "rose_ana_ukca_biomass",
    "seaice_field_reordering",
    "soil_dust_unittests",
    "soil_roughness_preproc_unittests",
    "soils_preproc_unittests",
    "soils_unittests",
    "sst_seaice_unittests",
    "topographic_index_unittests",
]
