[command]
default=ug-ants-launch regrid_to_mesh.py \
       =${source}  ${output} \
       =--target-mesh ${mesh_file} --target-mesh-name ${mesh_name} \
       =--horizontal-regrid-scheme ${regrid_scheme}
output_weights=ug-ants-launch regrid_to_mesh.py \
              =${source}  ${output} \
              =--target-mesh ${mesh_file} --target-mesh-name ${mesh_name} \
              =--horizontal-regrid-scheme ${regrid_scheme} \
              =--output-weights ${output_weights}
tolerance=ug-ants-launch regrid_to_mesh.py \
         =${source}  ${output} \
         =--target-mesh ${mesh_file} --target-mesh-name ${mesh_name} \
         =--horizontal-regrid-scheme ${regrid_scheme} \
         =--tolerance ${tolerance}
use_input_weights=ug-ants-launch regrid_to_mesh.py \
                 =${source}  ${output} \
                 =--target-mesh ${mesh_file} --target-mesh-name ${mesh_name} \
                 =--horizontal-regrid-scheme ${regrid_scheme} \
                 =--input-weights ${input_weights}

[env]
input_weights=${TEST_SOURCES_DIR}/global/regrid_weights/n96_to_C48/${scheme}_weights.nc
mesh_file=${TEST_SOURCES_DIR}/global/C48/mesh.nc
mesh_name=dynamics
output=${ROSE_DATA}/${ROSE_TASK_NAME}.nc
output_weights=${ROSE_DATA}/${ROSE_TASK_NAME}_weights.nc
regrid_scheme=${scheme}
source=${TEST_SOURCES_DIR}/global/n96/two_variable_multi_dimensional_synthetic_data.nc
tolerance=0.5
