[command]
default=ug-ants-launch generate_mask.py \
       =${source} ${output} --mask-type ${mask_type}

[env]
mask_type=${CYLC_TASK_PARAM_mask_type}
output=${ROSE_DATA}/${ROSE_TASK_NAME}.nc
source=${TEST_SOURCES_DIR}/global/C48/land_fraction.nc
