[command]
default=ug-ants-launch extract_mesh.py --mesh $mesh_path --mesh-name $mesh_name $output

[env]
mesh_name=dynamics
mesh_path=${TEST_SOURCES_DIR}/global/C24/multi_mesh.nc
output=${ROSE_DATA}/${ROSE_TASK_NAME}.nc
