[command]
default=true

# Copy selected files from root
[file:$ROSE_SUITE_DIR/share/fcm_make_ug_ants/build/CONTRIBUTING.rst]
source=${HOST_SOURCE_UG_ANTS_BASE}/CONTRIBUTING.rst

[file:$ROSE_SUITE_DIR/share/fcm_make_ug_ants/build/INSTALL.rst]
source=${HOST_SOURCE_UG_ANTS_BASE}/INSTALL.rst

[file:$ROSE_SUITE_DIR/share/fcm_make_ug_ants/build/LICENSE.txt]
source=${HOST_SOURCE_UG_ANTS_BASE}/LICENSE.txt

[file:$ROSE_SUITE_DIR/share/fcm_make_ug_ants/build/README.rst]
source=${HOST_SOURCE_UG_ANTS_BASE}/README.rst

# Copy /bin directory NOTE: rose task-run will add this to $PATH automatically
[file:$ROSE_SUITE_DIR/share/fcm_make_ug_ants/build/bin]
source=${HOST_SOURCE_UG_ANTS_BASE}/bin

# Copy /docs and /lib directories
[file:$ROSE_SUITE_DIR/share/fcm_make_ug_ants/build/docs]
source=${HOST_SOURCE_UG_ANTS_BASE}/docs

[file:$ROSE_SUITE_DIR/share/fcm_make_ug_ants/build/lib]
source=${HOST_SOURCE_UG_ANTS_BASE}/lib

[file:$ROSE_SUITE_DIR/share/fcm_make_ug_ants/build/pyproject.toml]
source=${HOST_SOURCE_UG_ANTS_BASE}/pyproject.toml

[file:$ROSE_SUITE_DIR/share/fcm_make_ug_ants/build/utils]
source=${HOST_SOURCE_UG_ANTS_BASE}/utils
