[command]
default=ug-ants-launch ugrid_to_XIOS.py ${source} ${output}
single_precision=ug-ants-launch ugrid_to_XIOS.py ${source} ${output} --cast-to-single

[env]
output=${ROSE_DATA}/${ROSE_TASK_NAME}.nc
source=${TEST_SOURCES_DIR}/global/C4/ugrid_to_xios.nc
