[env]
filelist=ancil_regrid_mesh_to_grid_bilinear.nc
        =ancil_regrid_mesh_to_grid_conservative.nc
        =ancil_regrid_mesh_to_grid_nearest.nc
        =ancil_regrid_mesh_to_grid_use_input_weights_bilinear.nc
        =ancil_regrid_mesh_to_grid_use_input_weights_conservative.nc
        =ancil_regrid_mesh_to_grid_use_input_weights_nearest.nc
        =ancil_regrid_mesh_to_grid_output_weights_bilinear.nc
        =ancil_regrid_mesh_to_grid_output_weights_conservative.nc
        =ancil_regrid_mesh_to_grid_output_weights_nearest.nc
        =ancil_regrid_mesh_to_grid_output_weights_bilinear_weights.nc
        =ancil_regrid_mesh_to_grid_output_weights_conservative_weights.nc
        =ancil_regrid_mesh_to_grid_output_weights_nearest_weights.nc
