[env]
filelist=ancil_regrid_grid_to_mesh_bilinear.nc
        =ancil_regrid_grid_to_mesh_conservative.nc
        =ancil_regrid_grid_to_mesh_nearest.nc
        =ancil_regrid_grid_to_mesh_bilinear_tolerance.nc
        =ancil_regrid_grid_to_mesh_conservative_tolerance.nc
        =ancil_regrid_grid_to_mesh_use_input_weights_bilinear.nc
        =ancil_regrid_grid_to_mesh_use_input_weights_conservative.nc
        =ancil_regrid_grid_to_mesh_use_input_weights_nearest.nc
        =ancil_regrid_grid_to_mesh_output_weights_bilinear.nc
        =ancil_regrid_grid_to_mesh_output_weights_conservative.nc
        =ancil_regrid_grid_to_mesh_output_weights_nearest.nc
        =ancil_regrid_grid_to_mesh_output_weights_bilinear_weights.nc
        =ancil_regrid_grid_to_mesh_output_weights_conservative_weights.nc
        =ancil_regrid_grid_to_mesh_output_weights_nearest_weights.nc
