name: CI documentation build and deploy

on:
    pull_request:
        branches: main
        types: [ready_for_review, review_requested]
    push:
        branches: main
    workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    build-docs:
        name: Build documentation with Sphinx
        runs-on: ubuntu-24.04
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: true
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup python environment
              uses: mamba-org/setup-micromamba@v2
              with:
                environment-file: environment.lock
                environment-name: ci-env
                cache-environment: true

            - name: Sphinx build
              shell: micromamba-shell {0}
              run: ./build_docs.sh

    deploy-docs:
        name: Deploy built documentation to GitHub pages
        if: ${{ github.event_name == 'push' && github.ref == 'main' }}
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-24.04
        steps:
            - name: Upload Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: docs/build/html
