name: Pull Request
run-name: ${{github.event.pull_request.number}} ${{github.event.pull_request.title}}
on:
    pull_request:
        branches:
            - main

jobs:
    run-tests:
        name: Run tests
        uses: ./.github/workflows/pytest.yml